sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t aisha/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true aisha/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-926270901348"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY